[formatter.alejandra]
command = "alejandra"
includes = ["*.nix"]

[formatter.yamlfmt]
command = "yamlfmt"
includes = ["*.yml", "*.yaml"]

[formatter.deno-fmt]
command = "deno"
options = ["fmt"]
includes = [
  "*.json",
  "*.jsonc",
  "*.toml",
  "*.md",
  "*.ts",
]
